import { Cookies } from "@/auth/types";
import { OAuthProvider } from "@/drizzle/schema";
import crypto from "crypto";
import { createDiscordOAuthClient } from "../providers/discord";

// A state is a large string which we generate and send along the request url. The discord sends the same state back to us. We just need to make sure that, what we sent them is the same thing they sent back to us.

const STATE_COOKIE_KEY = "oAuthState";
const CODE_VERIFIER_COOKIE_KEY = "oAuthCodeVerifier";

// Ten minutes in seconds
const COOKIE_EXPIRATION_SECONDS = 60 * 10;

// 1. A function for creating the state string :
export function createState(cookies: Pick<Cookies, "set">) {
  // Create a state :
  const state = crypto.randomBytes(64).toString("hex").normalize();

  // Store the state in cookies :
  cookies.set(STATE_COOKIE_KEY, state, {
    secure: true,
    httpOnly: true,
    sameSite: "lax",
    expires: Date.now() + COOKIE_EXPIRATION_SECONDS * 1000,
  });
  // console.log("State Generated by ME : ", state);
  return state;
}

// 2. A function to validate the state :
export function validateState(state: string, cookies: Pick<Cookies, "get">) {
  const cookieState = cookies.get(STATE_COOKIE_KEY)?.value;
  // console.log("State sent by Discord : ", cookieState);
  return cookieState === state;
}

// ______________________________________________________________________________________________

// 3. A function for creating code verifier :
export function createCodeVerifier(cookies: Pick<Cookies, "set">) {
  // Create a codeverifier string :
  const codeVerifier = crypto.randomBytes(64).toString("hex").normalize();

  // Store the codeVerifier in cookies :
  cookies.set(CODE_VERIFIER_COOKIE_KEY, codeVerifier, {
    secure: true,
    httpOnly: true,
    sameSite: "lax",
    expires: Date.now() + COOKIE_EXPIRATION_SECONDS * 1000,
  });
  return codeVerifier;
}

// 4. A function to get the code verifier from the OAuth provider :
export function getCodeVerifier(cookies: Pick<Cookies, "get">) {
  const codeVerifier = cookies.get(CODE_VERIFIER_COOKIE_KEY)?.value;
  return codeVerifier;
}

// ______________________________________________________________________________________________

// 5. A function to match the "OAuthClient" with the providers :
export function getOAuthClient(provider: OAuthProvider) {
  switch (provider) {
    case "discord":
      return createDiscordOAuthClient();

    case "github":
      return createDiscordOAuthClient();

    default:
      throw new Error(`Invalid provider : ${provider satisfies never}`);
  }
}
